/**
 * content-loader.js
 * Reads SITE from content.js and populates every page.
 * Do NOT edit this file.
 */
(function () {
  if (typeof SITE === 'undefined') {
    console.error('[content-loader] content.js must be loaded first.');
    return;
  }

  /* ── helpers ──────────────────────────────────────────────────── */

  function get(path) {
    return path.split('.').reduce(function (o, k) { return o && o[k]; }, SITE);
  }

  function wa(message) {
    return 'https://wa.me/' + SITE.hotel.whatsapp +
           (message ? '?text=' + encodeURIComponent(message) : '');
  }

  function el(tag, attrs, html) {
    var node = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) { node.setAttribute(k, attrs[k]); });
    if (html !== undefined) node.innerHTML = html;
    return node;
  }

  /* ── fill data-c text nodes ────────────────────────────────────── */

  function populateText() {
    document.querySelectorAll('[data-c]').forEach(function (node) {
      var val = get(node.dataset.c);
      if (val !== undefined) node.textContent = val;
    });
  }

  /* ── update all WhatsApp hrefs ─────────────────────────────────── */

  function populateWaLinks() {
    var generic = 'Hi, I\'d like to make a reservation at Hotel Mount Kailash.';
    document.querySelectorAll('[data-wa]').forEach(function (a) {
      a.href = wa(a.dataset.wa || generic);
    });
  }

  /* ── update social links ───────────────────────────────────────── */

  function populateSocial() {
    var fb = document.querySelector('[data-social="facebook"]');
    if (fb) fb.href = SITE.hotel.facebook;
    var ig = document.querySelector('[data-social="instagram"]');
    if (ig) ig.href = SITE.hotel.instagram;
  }

  /* ════════════════════════════════════════════════════════════════
     PAGE GENERATORS
     ════════════════════════════════════════════════════════════════ */

  /* ── helpers ─────────────────────────────────────────────────── */

  function primaryImage(room) {
    var imgs = room.images || (room.image ? [room.image] : []);
    return imgs.length > 0 ? imgs[0] : '';
  }

  /* ── homepage: room cards ──────────────────────────────────────── */

  function buildHomepageRooms() {
    var grid = document.getElementById('rooms-homepage');
    if (!grid) return;
    grid.innerHTML = SITE.rooms.map(function (room) {
      var shown = room.features.filter(function (f) { return f.enabled; }).slice(0, 3);
      var lis = shown.map(function (f) {
        return '<li><i class="fas ' + f.icon + '"></i> ' + f.label + '</li>';
      }).join('');
      return '<div class="room-card">' +
        '<div class="room-image">' +
          '<img src="img/' + primaryImage(room) + '" alt="' + room.name + '">' +
          '<div class="room-price">From ' + room.price + '/night</div>' +
        '</div>' +
        '<div class="room-details">' +
          '<h3>' + room.name + '</h3>' +
          '<p>' + room.shortDesc + '</p>' +
          '<ul class="room-amenities">' + lis + '</ul>' +
          '<a href="rooms.html#' + room.id + '" class="btn btn-secondary">View Details</a>' +
        '</div>' +
      '</div>';
    }).join('');
  }

  /* ── homepage: features (In-House Delights) ────────────────────── */

  function buildFeatures() {
    var grid = document.getElementById('features-grid');
    if (!grid) return;
    grid.innerHTML = SITE.features.filter(function (f) { return f.enabled; }).map(function (f) {
      return '<div class="feature-item">' +
        '<div class="feature-icon"><i class="fas ' + f.icon + '"></i></div>' +
        '<h3>' + f.title + '</h3>' +
        '<p>' + f.description + '</p>' +
      '</div>';
    }).join('');
  }

  /* ── homepage: testimonials ─────────────────────────────────────── */

  function buildTestimonials() {
    var container = document.getElementById('testimonials-container');
    if (!container) return;
    var active = SITE.testimonials.filter(function (t) { return t.enabled; });
    var slides = active.map(function (t, i) {
      return '<div class="testimonial-slide' + (i === 0 ? ' active' : '') + '">' +
        '<div class="testimonial-content">' +
          '<div class="quote-icon"><i class="fas fa-quote-left"></i></div>' +
          '<p>"' + t.text + '"</p>' +
          '<div class="testimonial-author"><div class="author-info">' +
            '<h4>' + t.author + '</h4>' +
            '<span>' + t.location + '</span>' +
          '</div></div>' +
        '</div>' +
      '</div>';
    }).join('');
    var dots = active.map(function (_, i) {
      return '<span class="dot' + (i === 0 ? ' active' : '') + '" data-slide="' + i + '"></span>';
    }).join('');
    container.innerHTML = slides +
      '<div class="testimonial-controls"><div class="testimonial-dots">' + dots + '</div></div>';
  }

  /* ── rooms page: detailed room items ───────────────────────────── */

  function buildRoomsPage() {
    var grid = document.getElementById('rooms-page');
    if (!grid) return;
    grid.innerHTML = SITE.rooms.map(function (room) {
      var imgs = room.images || (room.image ? [room.image] : []);
      var mainImg = imgs[0] || '';

      /* gallery HTML — only render strip if there are multiple images */
      var galleryHtml;
      if (imgs.length > 1) {
        var thumbHtml = imgs.map(function (img, i) {
          return '<img class="thumbnail' + (i === 0 ? ' active' : '') + '" ' +
                 'src="img/' + img + '" ' +
                 'data-full="img/' + img + '" ' +
                 'alt="' + room.name + ' — photo ' + (i + 1) + '">';
        }).join('');
        galleryHtml =
          '<div class="room-gallery">' +
            '<div class="main-image"><img src="img/' + mainImg + '" alt="' + room.name + '"></div>' +
            '<div class="gallery-nav">' +
              '<button class="gallery-prev" aria-label="Previous"><i class="fas fa-chevron-left"></i></button>' +
              '<div class="thumbnail-images">' + thumbHtml + '</div>' +
              '<button class="gallery-next" aria-label="Next"><i class="fas fa-chevron-right"></i></button>' +
            '</div>' +
          '</div>';
      } else {
        galleryHtml =
          '<div class="room-gallery">' +
            '<div class="main-image"><img src="img/' + mainImg + '" alt="' + room.name + '"></div>' +
          '</div>';
      }

      var featureItems = room.features.filter(function (f) { return f.enabled; }).map(function (f) {
        return '<li><i class="fas ' + f.icon + '"></i> ' + f.label + '</li>';
      }).join('');
      var descHtml = room.longDesc.map(function (p) { return '<p>' + p + '</p>'; }).join('');
      var msg = 'Hi, I\'d like to book the ' + room.name + ' at Hotel Mount Kailash. Please share availability.';

      return '<div class="room-item ' + room.id + '" id="' + room.id + '">' +
        '<div class="room-images">' + galleryHtml + '</div>' +
        '<div class="room-details">' +
          '<div class="room-heading">' +
            '<h2>' + room.name + '</h2>' +
            '<div class="room-price">From ' + room.price + '<span>/night</span></div>' +
          '</div>' +
          '<div class="room-description">' + descHtml + '</div>' +
          '<div class="room-features">' +
            '<h3>Room Features</h3>' +
            '<ul class="features-list">' + featureItems + '</ul>' +
          '</div>' +
          '<div class="room-booking">' +
            '<a href="' + wa(msg) + '" target="_blank" class="btn btn-primary">' +
              '<i class="fab fa-whatsapp"></i> Book via WhatsApp' +
            '</a>' +
          '</div>' +
        '</div>' +
      '</div>';
    }).join('');

    /* also rebuild filter tabs to match rooms */
    var tabs = document.querySelector('.filter-tabs');
    if (tabs) {
      var btns = '<button class="filter-tab active" data-filter="all">All Rooms</button>';
      SITE.rooms.forEach(function (room) {
        btns += '<button class="filter-tab" data-filter="' + room.id + '">' + room.name + 's</button>';
      });
      tabs.innerHTML = btns;
    }
  }

  /* ── rooms page: amenities ──────────────────────────────────────── */

  function buildAmenities() {
    var grid = document.getElementById('amenities-grid');
    if (!grid) return;
    grid.innerHTML = SITE.amenities.map(function (cat) {
      var items = cat.items.filter(function (i) { return i.enabled; })
        .map(function (i) { return '<li>' + i.label + '</li>'; }).join('');
      return '<div class="amenity-category">' +
        '<h3><i class="fas ' + cat.icon + '"></i> ' + cat.category + '</h3>' +
        '<ul>' + items + '</ul>' +
      '</div>';
    }).join('');
  }

  /* ── about page: philosophy ─────────────────────────────────────── */

  function buildPhilosophy() {
    var grid = document.getElementById('philosophy-grid');
    if (!grid) return;
    grid.innerHTML = SITE.about.philosophy.filter(function (p) { return p.enabled; }).map(function (p) {
      return '<div class="philosophy-item">' +
        '<div class="philosophy-icon"><i class="fas ' + p.icon + '"></i></div>' +
        '<h3>' + p.title + '</h3>' +
        '<p>' + p.description + '</p>' +
      '</div>';
    }).join('');
  }

  /* ── about page: team ───────────────────────────────────────────── */

  function buildTeam() {
    var grid = document.getElementById('team-grid');
    if (!grid) return;
    grid.innerHTML = SITE.about.team.filter(function (m) { return m.enabled; }).map(function (m) {
      return '<div class="team-member">' +
        '<div class="member-image"><img src="img/' + m.image + '" alt="' + m.name + '"></div>' +
        '<div class="member-info">' +
          '<h3>' + m.name + '</h3>' +
          '<span class="position">' + m.position + '</span>' +
          '<p>' + m.bio + '</p>' +
        '</div>' +
      '</div>';
    }).join('');
  }

  /* ── gallery page ───────────────────────────────────────────────── */

  function buildGallery() {
    var g = SITE.gallery;
    if (!g) return;

    /* filter tabs */
    var tabs = document.getElementById('gallery-filter-tabs');
    if (tabs) {
      var tabHtml = '<button class="filter-tab active" data-filter="all">All Photos</button>';
      g.categories.forEach(function (cat) {
        tabHtml += '<button class="filter-tab" data-filter="' + cat.id + '">' + cat.label + '</button>';
      });
      tabs.innerHTML = tabHtml;
    }

    /* photo grid */
    var grid = document.getElementById('gallery-grid');
    if (!grid) return;
    var enabled = g.photos.filter(function (p) { return p.enabled; });
    grid.innerHTML = enabled.map(function (p) {
      return '<div class="gallery-item ' + p.category + '">' +
        '<img src="img/' + p.image + '" alt="' + p.title + '">' +
        '<div class="gallery-caption">' +
          '<h3>' + p.title + '</h3>' +
          '<p>' + p.caption + '</p>' +
        '</div>' +
      '</div>';
    }).join('');
  }

  /* ── contact page: FAQ ──────────────────────────────────────────── */

  function buildFaq() {
    var acc = document.getElementById('faq-accordion');
    if (!acc) return;
    acc.innerHTML = SITE.contact.faq.filter(function (f) { return f.enabled; }).map(function (f) {
      return '<div class="accordion-item">' +
        '<div class="accordion-header">' +
          '<h3>' + f.question + '</h3>' +
          '<span class="accordion-icon"><i class="fas fa-plus"></i></span>' +
        '</div>' +
        '<div class="accordion-content"><p>' + f.answer + '</p></div>' +
      '</div>';
    }).join('');
  }

  /* ════════════════════════════════════════════════════════════════
     BOOT — detect page and run builders
     ════════════════════════════════════════════════════════════════ */

  document.addEventListener('DOMContentLoaded', function () {
    populateText();
    populateWaLinks();
    populateSocial();

    var page = document.body.dataset.page;

    if (page === 'home') {
      buildHomepageRooms();
      buildFeatures();
      buildTestimonials();
    }

    if (page === 'rooms') {
      buildRoomsPage();
      buildAmenities();
    }

    if (page === 'about') {
      buildPhilosophy();
      buildTeam();
    }

    if (page === 'contact') {
      buildFaq();
    }

    if (page === 'gallery') {
      buildGallery();
    }
  });

})();
